---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-postfix",
         tags: ["create", "update"] 
       }
     - {
         role: "sa-secure-audit-lynis",
         tags: ["create", "update"]
       }

  tasks:

    - debug: msg="Tasks section"



